name: Update Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python (for generating docs, if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install documentation tools (optional)
        run: |
          pip install mkdocs  # Example for MkDocs
          pip install mkdocs-material

      - name: Generate Documentation
        run: |
          # This is an example for generating static docs with mkdocs
          if [ -f mkdocs.yml ]; then
            mkdocs build
          else
            echo "No mkdocs.yml found, skipping documentation generation"
          fi

      - name: Check for Markdown files
        run: |
          # Ensure README.md exists
          if [ ! -f README.md ]; then
            echo "Error: README.md file is missing"
            exit 1
          fi
          
          # You can extend this check for other documentation files
          echo "Documentation files are valid."
